# Generated by Django 5.0.6 on 2024-06-18 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inv', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategorias',
            options={'verbose_name': 'SubCategoria', 'verbose_name_plural': 'SubCategorias'},
        ),
        migrations.AddField(
            model_name='subcategorias',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Inv.categorias'),
        ),
        migrations.AddField(
            model_name='subcategorias',
            name='descripcion',
            field=models.CharField(default=1, help_text='descripcion subcategoria', max_length=100, verbose_name='descripcion-sub'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categorias',
            name='descripcion',
            field=models.CharField(help_text='descripcion', max_length=100, unique=True, verbose_name='descripcion'),
        ),
        migrations.AlterUniqueTogether(
            name='subcategorias',
            unique_together={('categoria', 'descripcion')},
        ),
    ]
