# Generated by Django 5.0.6 on 2024-06-19 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inv', '0002_alter_subcategorias_options_subcategorias_categoria_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marca',
            options={'verbose_name': 'marca', 'verbose_name_plural': 'marcas'},
        ),
        migrations.AddField(
            model_name='marca',
            name='descripcion',
            field=models.CharField(default=1, help_text='descripcion marca', max_length=100, verbose_name='descripcion-marca'),
            preserve_default=False,
        ),
    ]
