# Generated by Django 5.0.6 on 2024-06-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inv', '0003_alter_marca_options_marca_descripcion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marca',
            options={'verbose_name': 'marca', 'verbose_name_plural': 'marca'},
        ),
        migrations.AlterField(
            model_name='marca',
            name='descripcion',
            field=models.CharField(help_text='descripcion marca', max_length=100, unique=True, verbose_name='descripcion-marca'),
        ),
    ]
