# Generated by Django 5.0.6 on 2024-06-20 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inv', '0004_alter_marca_options_alter_marca_descripcion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unidadmedida',
            options={'verbose_name': 'marca', 'verbose_name_plural': 'marca'},
        ),
        migrations.AddField(
            model_name='unidadmedida',
            name='descripcion',
            field=models.CharField(default=1, help_text='descripcion marca', max_length=100, unique=True, verbose_name='unidad de medida'),
            preserve_default=False,
        ),
    ]
