# Generated by Django 5.0.6 on 2024-06-25 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inv', '0010_alter_categorias_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorias',
            options={'permissions': [('view_categoria', 'Can view categorias'), ('add_categoria', 'Can add categoria'), ('change_categoria', 'Puede cambiar MiModelo'), ('delete_categoria', 'Can delete categoria')], 'verbose_name': 'Categoria'},
        ),
        migrations.AlterModelOptions(
            name='unidadmedida',
            options={'verbose_name': 'unidad de medida', 'verbose_name_plural': 'unidades de medida'},
        ),
    ]
