# Generated by Django 5.0.6 on 2024-06-25 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inv', '0011_alter_categorias_options_alter_unidadmedida_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorias',
            options={'verbose_name': 'Categoria'},
        ),
    ]
