# Generated by Django 5.0.6 on 2024-07-04 16:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Catastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha-creacion')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='fecha-modificacion')),
                ('usuario_modificacion', models.IntegerField(blank=True, null=True)),
                ('nombre_propietario', models.CharField(max_length=100)),
                ('email', models.EmailField(default='s/n', max_length=254)),
                ('telefono', models.CharField(default='s/n', max_length=20)),
                ('direccion', models.CharField(default='s/n', max_length=255)),
                ('representante_legal', models.CharField(blank=True, max_length=100)),
                ('numero_oficial', models.CharField(max_length=8)),
                ('clave_catastral', models.CharField(max_length=8)),
                ('superficie', models.DecimalField(decimal_places=2, max_digits=10)),
                ('calle', models.CharField(default='s/n', max_length=255)),
                ('numero_exterior', models.CharField(default='s/n', max_length=6)),
                ('numero_interior', models.CharField(default='s/n', max_length=6)),
                ('colonia', models.CharField(default='s/n', max_length=100)),
                ('delegacion', models.CharField(default='s/n', max_length=100)),
                ('codigo_postal', models.CharField(default='s/n', max_length=5)),
                ('manzana', models.CharField(max_length=3)),
                ('lote', models.CharField(max_length=3)),
                ('fracciones', models.CharField(blank=True, max_length=50, null=True)),
                ('parcelas', models.CharField(blank=True, max_length=50, null=True)),
                ('condominio', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='NO')),
                ('unidad', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre_condominio', models.CharField(blank=True, max_length=100, null=True)),
                ('valor_unitario_zona', models.IntegerField(default=0)),
                ('valor_unitario_predio', models.IntegerField(default=0)),
                ('valor_unitario_provicional', models.IntegerField(default=0)),
                ('superficie_construccion', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('uso_suelo', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='NO')),
                ('tasa', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('frente_comun', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='NO')),
                ('valor_fiscal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_alta', models.DateTimeField()),
                ('fecha_vigencia', models.DateField(blank=True, null=True)),
                ('clave_anterior', models.CharField(blank=True, max_length=8, null=True)),
                ('comentario', models.TextField(default='s/n')),
                ('tipo', models.CharField(choices=[('URBANO', 'URBANO'), ('RUSTICO', 'RUSTICO'), ('RURAL', 'RURAL')], default='URBANO')),
                ('minicipio', models.CharField(default='Ensenada', max_length=50)),
                ('estado', models.CharField(default='Baja California Norte', max_length=50)),
                ('pais', models.CharField(default='Mexico', max_length=50)),
                ('sector', models.CharField(default='s/n', max_length=80)),
                ('tipo_persona', models.CharField(choices=[('MORAL', 'MORAL'), ('FISICA', 'FISICA')], default='FISICA')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True, verbose_name='estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha-creacion')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='fecha-modificacion')),
                ('usuario_modificacion', models.IntegerField(blank=True, null=True)),
                ('colindancias', models.CharField(blank=True, max_length=150)),
                ('rfc', models.CharField(blank=True, max_length=13)),
                ('curp', models.CharField(blank=True, max_length=18)),
                ('pensionado', models.BooleanField(default=False)),
                ('nombre_casada', models.CharField(blank=True, max_length=80)),
                ('observaciones', models.CharField(blank=True, max_length=150)),
                ('opcion_tramite', models.CharField(choices=[('TIPOS DE VALORES', 'TIPOS DE VALORES'), ('RA3 - RECTIFICACION VALORES', 'RA3 - RECTIFICACION VALORES'), ('RA4 - RECTIFICACION NOMBRE', 'RA4 - RECTIFICACION NOMBRE'), ('RA5 - RECTIFICACION DIRECION', 'RA5 - RECTIFICACION DIRECION'), ('RA6 - CAMBIO CLAVE', 'RA6 - CAMBIO CLAVE'), ('RA7 - RECTIFICACION TASA', 'RA7 - RECTIFICACION TASA'), ('RA8 - RECTIFICACION VIGENCIA', 'RA8 - RECTIFICACION VIGENCIA'), ('RA9 - SITUACION LEGAL', 'RA9 - SITUACION LEGAL'), ('RA10 - RECTIFICACION COLINDANCIAS', 'RA10 - RECTIFICACION COLINDANCIAS'), ('RA11 - RECTIFICACION ANTECEDENTE', 'RA11 - RECTIFICACION ANTECEDENTE')], default='TIPOS DE VALORES')),
                ('numero_tramite', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(6)])),
                ('datos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ControlUrbano.catastro')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
