# Generated by Django 5.0.6 on 2024-07-04 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControlUrbano', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catastro',
            name='distrito',
            field=models.CharField(default='01', max_length=2),
        ),
        migrations.AddField(
            model_name='catastro',
            name='domicilio',
            field=models.CharField(default='s/n', max_length=180),
        ),
    ]
