# Generated by Django 5.0.6 on 2024-07-04 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControlUrbano', '0003_alter_notificaciones_datos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificaciones',
            name='datos',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ControlUrbano.catastro'),
        ),
    ]
