# Generated by Django 5.0.6 on 2024-07-04 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControlUrbano', '0005_alter_notificaciones_datos'),
    ]

    operations = [
        migrations.AddField(
            model_name='catastro',
            name='castigo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='catastro',
            name='fecha_notificacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
